server:
  port: 3003

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/garage?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: validate
      show-sql: true
    properties:
      hibernate.jdbc.time_zone: UTC
  flyway:
    enabled: true
